### ISSUE TITLE
URL context

### ISSUE THREAD

**Issue by alee** [warmdev/radiant-mod-docker#1]
I've put it up at https://miracle.comses.net/marketing/ but it displays "Error: invalid first argument" when I load the page.

Also, is there a reason you're using /marketing instead of something like /radiant ?

**Comment by warmdev** [comment]
That is likely because the data folder was mounted at an incorrect location. For example, the correct path for the `luxe` `runLog.csv` file should be `/srv/shiny-server/data/luxe/log/runLog.csv`. Also, when no `project` is provided by url, it loads `luxe` data by default.

Naming: This is because `Radiant` is organized as four apps: `base`, `quant`, `analytics` and `marketing`, with each one having more functionalities than the previous one, and `marketing` is the one with the most functions. If you rename the `marketing` folder to `radiant` everything should still work, since it's all relative path inside the system, and `marketing` is not referred by any other apps.

**Comment by alee** [comment]
I checked the docker image and the path is correct but the permissions look wrong. Here's what I see:

```
# ls -al /srv/shiny-server
total 28
drwxr-xr-x. 7 root root 4096 Sep 21 05:59 .
drwxr-xr-x. 4 root root 4096 Sep 17 20:29 ..
drwxr-xr-x. 5 root root 4096 Sep 17 20:29 analytics
drwxr-xr-x. 6 root root 4096 Sep 17 20:29 base
drwxr-sr-x. 3 1000 3103 4096 Sep 21 05:56 data
lrwxrwxrwx. 1 root root   38 Sep 17 20:12 index.html -> /opt/shiny-server/samples/welcome.html
drwxr-xr-x. 5 root root 4096 Sep 17 20:29 marketing
drwxr-xr-x. 5 root root 4096 Sep 17 20:29 quant
lrwxrwxrwx. 1 root root   37 Sep 17 20:12 sample-apps -> /opt/shiny-server/samples/sample-apps

# ls -al /srv/shiny-server/data/luxe/log
total 88
drwx------. 2 1000 3103  4096 Aug 26 17:36 .
drwx------. 4 1000 3103  4096 Sep  2 02:43 ..
-rw-r--r--. 1 1000 3103 75194 Aug 17 20:38 runLog.csv
```

Should I change the permissions or is this something that needs extra configuration when running or building the docker image?

**Comment by warmdev** [comment]
Yes it is a permission problem. The Shiny Server in the container runs as the `shiny` user by default, which has a uid of 999 and gid of 1000. We can fix it either from the host or the container. From the host, change the user's primary group to a group with gid of 1000 (the user that owns the data folder). Or from the container, create a user that matches the uid/gid of the host and run Radiant as that user (need to change the Dockerfile and the shiny-server.conf file). In the long run, we need to set up uniform uid/gids for the host and the containers (Calvin already did this for the containers).

**Comment by warmdev** [comment]
If you can add the following to the Dockerfile (right before `EXPOSE 3838`) and rebuild the image it should work. Adding it to the end of the file also means you don't have to rebuild the entire image which takes a long time.

```
# Run Shiny as a different user
RUN useradd -u 1000 miracle
RUN sed -i -e 's/run_as shiny/run_as miracle/g' /etc/shiny-server/shiny-server.conf
RUN mkdir -p /var/log/shiny-server
RUN touch /var/log/shiny-server.log
RUN chown miracle:miracle /var/log/shiny-server.log
RUN chown miracle:miracle /var/log/shiny-server
USER miracle
```

**Comment by alee** [comment]
Fixed, deployed to https://miracle.comses.net/radiant - thanks!
